joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000
  joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

joint_group_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    joint_1:
      pid: {p: 500.0, i: 0.0, d: 10.0}
    joint_2:
      pid: {p: 500.0, i: 0.0, d: 10.0}
    joint_3:
      pid: {p: 500.0, i: 0.0, d: 10.0}
    joint_4:
      pid: {p: 500.0, i: 0.0, d: 10.0}
    joint_5:
      pid: {p: 100.0, i: 0.0, d: 10.0}
    joint_6:
      pid: {p: 100.0, i: 0.0, d: 10.0}


joint_group_effort_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
