finger_group_action_controller:
    action_monitor_rate: 100
    type: effort_controllers/GripperActionController
    joint: finger_joint
    gains: 
        finger_joint: {p: 10.0, i: 0.0, d: 0.01}         
     
    
gen3_lite_2f_gripper_action_controller:
  type: position_controllers/GripperActionController
  action_monitor_rate: 100
  joints: 
    - right_finger_bottom_joint
    - right_finger_tip_joint
    - left_finger_bottom_joint
    - left_finger_tip_joint  

